[build]
  command = "gradle wasmJsBrowserProductionWebpack"
  publish = "composeApp/build/kotlin-webpack/wasmJs/productionExecutable"

[build.environment]
  GRADLE_VERSION = "8.5"
  JAVA_VERSION = "17"